// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (user_id, post_id)
SELECT
  $1,
  posts.id
FROM posts
JOIN feed_follows ON feed_follows.feed_id = posts.feed_id
WHERE posts.id = $2
  AND feed_follows.user_id = $1
ON CONFLICT (user_id, post_id)
DO UPDATE SET post_id = EXCLUDED.post_id
RETURNING bookmarks.user_id, bookmarks.post_id, bookmarks.created_at
`

type CreateBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark, arg.UserID, arg.PostID)
	var i Bookmark
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND post_id = $2
`

type DeleteBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.UserID, arg.PostID)
	return err
}

const getBookmarkedPosts = `-- name: GetBookmarkedPosts :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.description, posts.published_at, posts.url, posts.feed_id FROM posts
JOIN bookmarks ON posts.id = bookmarks.post_id
WHERE bookmarks.user_id = $1
AND (
  $2::timestamp IS NULL
  OR (posts.published_at, posts.id) < (
    $2,
    $3::uuid
  )
)
ORDER BY posts.published_at DESC, posts.id DESC
LIMIT $4
`

type GetBookmarkedPostsParams struct {
	UserID            uuid.UUID
	CursorPublishedAt sql.NullTime
	CursorID          uuid.NullUUID
	Limit             int32
}

func (q *Queries) GetBookmarkedPosts(ctx context.Context, arg GetBookmarkedPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarkedPosts,
		arg.UserID,
		arg.CursorPublishedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Url,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
