// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completePasswordReset = `-- name: CompletePasswordReset :execrows
WITH valid_reset AS (
    DELETE FROM password_resets
    WHERE user_id = $1
      AND otp_hash = $2
      AND expires_at > $3
    RETURNING user_id
)
UPDATE users
SET password_hash = $4,
    updated_at = $5
WHERE id = (SELECT user_id FROM valid_reset)
`

type CompletePasswordResetParams struct {
	UserID       uuid.UUID
	OtpHash      string
	ExpiresAt    time.Time
	PasswordHash string
	UpdatedAt    time.Time
}

func (q *Queries) CompletePasswordReset(ctx context.Context, arg CompletePasswordResetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completePasswordReset,
		arg.UserID,
		arg.OtpHash,
		arg.ExpiresAt,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPasswordResetByUser = `-- name: GetPasswordResetByUser :one
SELECT user_id, otp_hash, expires_at, created_at
FROM password_resets
WHERE user_id = $1
`

type GetPasswordResetByUserRow struct {
	UserID    uuid.UUID
	OtpHash   string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) GetPasswordResetByUser(ctx context.Context, userID uuid.UUID) (GetPasswordResetByUserRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByUser, userID)
	var i GetPasswordResetByUserRow
	err := row.Scan(
		&i.UserID,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const savePasswordReset = `-- name: SavePasswordReset :exec
INSERT INTO password_resets (user_id, otp_hash,created_at,expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET otp_hash = EXCLUDED.otp_hash,
expires_at = EXCLUDED.expires_at,
created_at = EXCLUDED.created_at
`

type SavePasswordResetParams struct {
	UserID    uuid.UUID
	OtpHash   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) SavePasswordReset(ctx context.Context, arg SavePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, savePasswordReset,
		arg.UserID,
		arg.OtpHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
