// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_status.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const markPostAsRead = `-- name: MarkPostAsRead :one
INSERT INTO read_posts (user_id, post_id)
SELECT $1, posts.id
FROM posts
JOIN feed_follows ON feed_follows.feed_id = posts.feed_id
WHERE posts.id = $2
  AND feed_follows.user_id = $1
ON CONFLICT (user_id, post_id)
DO UPDATE SET post_id = EXCLUDED.post_id
RETURNING read_posts.user_id, read_posts.post_id, read_posts.read_at
`

type MarkPostAsReadParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) MarkPostAsRead(ctx context.Context, arg MarkPostAsReadParams) (ReadPost, error) {
	row := q.db.QueryRowContext(ctx, markPostAsRead, arg.UserID, arg.PostID)
	var i ReadPost
	err := row.Scan(&i.UserID, &i.PostID, &i.ReadAt)
	return i, err
}

const markPostAsUnread = `-- name: MarkPostAsUnread :exec
DELETE FROM read_posts
WHERE user_id = $1 AND post_id = $2
`

type MarkPostAsUnreadParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) MarkPostAsUnread(ctx context.Context, arg MarkPostAsUnreadParams) error {
	_, err := q.db.ExecContext(ctx, markPostAsUnread, arg.UserID, arg.PostID)
	return err
}
